In [43]:
import pandas as pd
import numpy as np
import seaborn as sns

In [44]:
df = pd.read_csv('emails.csv')

In [45]:
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [46]:
df.shape

(5719, 2)

In [47]:
df = df.iloc[:,:2]

In [48]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5714  Subject: re : research and development charges...     0
5715  Subject: re : receipts from visit  jim ,  than...     0
5716  Subject: re : enron case study update  wow ! a...     0
5717  Subject: re : interest  david ,  please , call...     0
5718  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5719 rows x 2 columns]

In [49]:
df['spam'].value_counts()

0    4358
1    1361
Name: spam, dtype: int64

In [50]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [51]:
df.dropna(inplace=True)

In [52]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [53]:
df['spam'].value_counts()

0    4358
1    1361
Name: spam, dtype: int64

# Separate x and y

In [54]:
x = df.text.values

In [55]:
y = df.spam.values

In [56]:
y

array([1, 1, 1, ..., 0, 0, 0])

# split dataset into train and test

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

# Data preprocessing

In [59]:
from sklearn.feature_extraction.text import CountVectorizer

In [60]:
cv=CountVectorizer()

In [61]:
x_train=cv.fit_transform(xtrain)

In [62]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 2, ..., 0, 0, 0]])

# naive bayes

In [63]:
from sklearn.naive_bayes import MultinomialNB

In [64]:
model = MultinomialNB()
model.fit(x_train,ytrain)

MultinomialNB()

In [65]:
x_test = cv.transform(xtest)

In [66]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [67]:
model.predict(x_test)

array([0, 0, 0, ..., 0, 0, 1])

In [68]:
ytest

array([0, 0, 0, ..., 0, 0, 1])

In [69]:
model.score(x_test,ytest)

0.9912587412587412

# prediction

In [70]:
emails = ['hey i am lokking for machine learning tutorial in begali language','hey you win an iphone x giveaway for free please do the survey']

In [71]:
cv_emails = cv.transform(emails)

In [72]:
model.predict(cv_emails)

array([0, 1])

# performance matrix


In [73]:
pred = model.predict(x_test)

In [74]:
pred

array([0, 0, 0, ..., 0, 0, 1])

# accuracy

In [75]:
from sklearn.metrics import accuracy_score

In [76]:
accuracy_score(ytest,pred)

0.9912587412587412

# confusion matrix

In [77]:
from sklearn.metrics import confusion_matrix

In [78]:
confusion_matrix(ytest,pred)

array([[872,   7],
       [  3, 262]])

# report

In [79]:
from sklearn.metrics import classification_report

In [80]:
print(classification_report(ytest,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       879
           1       0.97      0.99      0.98       265

    accuracy                           0.99      1144
   macro avg       0.99      0.99      0.99      1144
weighted avg       0.99      0.99      0.99      1144

