In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [15]:
df = pd.read_csv('emails.csv')

In [16]:
df.head(5)

text spam Unnamed: 2  \
0  Subject: naturally irresistible your corporate...    1        NaN   
1  Subject: the stock trading gunslinger  fanny i...    1        NaN   
2  Subject: unbelievable new homes made easy  im ...    1        NaN   
3  Subject: 4 color printing special  request add...    1        NaN   
4  Subject: do not have money , get software cds ...    1        NaN   

  Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        NaN        NaN        NaN   

  Unnamed: 9  ... Unnamed: 100 Unnamed: 101 Unnamed: 102 Unnamed: 103  \
0        NaN  ...          NaN          NaN          NaN          NaN   
1        NaN  ...          NaN          NaN          NaN          NaN   
2        NaN  ...          NaN          NaN          NaN          NaN   
3        NaN  ...          NaN          NaN          NaN          NaN   
4        NaN  ...          NaN          NaN          NaN          NaN   

  Unnamed: 104 Unnamed: 105 Unnamed: 106 Unnamed: 107 Unnamed: 108  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN          NaN          NaN          NaN          NaN   
2          NaN          NaN          NaN          NaN          NaN   
3          NaN          NaN          NaN          NaN          NaN   
4          NaN          NaN          NaN          NaN          NaN   

  Unnamed: 109  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  

[5 rows x 110 columns]

In [5]:
df.shape

(5730, 110)

In [20]:
df = df.iloc[:,:2]

In [21]:
df

text spam
0     Subject: naturally irresistible your corporate...    1
1     Subject: the stock trading gunslinger  fanny i...    1
2     Subject: unbelievable new homes made easy  im ...    1
3     Subject: 4 color printing special  request add...    1
4     Subject: do not have money , get software cds ...    1
...                                                 ...  ...
5725  Subject: re : research and development charges...    0
5726  Subject: re : receipts from visit  jim ,  than...    0
5727  Subject: re : enron case study update  wow ! a...    0
5728  Subject: re : interest  david ,  please , call...    0
5729  Subject: news : aurora 5 . 2 update  aurora ve...    0

[5730 rows x 2 columns]

In [23]:
df['spam'].value_counts()

0                                                                                               4359
1                                                                                               1367
 its termination would not  have such a phenomenal impact on the power situation .  however        1
 mr suresh prabhu                                                                                  1
Name: spam, dtype: int64

In [24]:
df.isnull().sum()

text    0
spam    2
dtype: int64

In [25]:
df.dropna(inplace=True)

In [26]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [27]:
df['spam'].value_counts()

0                                                                                               4359
1                                                                                               1367
 its termination would not  have such a phenomenal impact on the power situation .  however        1
 mr suresh prabhu                                                                                  1
Name: spam, dtype: int64

# Separate x and y

In [29]:
x = df.text.values

In [30]:
y = df.spam.values

In [31]:
y

array(['1', '1', '1', ..., '0', '0', '0'], dtype=object)

# split dataset into train and test

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

# Data preprocessing

In [37]:
from sklearn.feature_extraction.text import CountVectorizer

In [38]:
cv=CountVectorizer()

In [39]:
x_train=cv.fit_transform(xtrain)

In [40]:
x_train.toarray()

array([[4, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0]])

# naive bayes

In [42]:
from sklearn.naive_bayes import MultinomialNB

In [43]:
model = MultinomialNB()
model.fit(x_train,ytrain)

MultinomialNB()

In [44]:
x_test = cv.transform(xtest)

In [45]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [51]:
model.predict(x_test)

array(['0', '1', '0', ..., '0', '1', '1'], dtype='<U92')

In [52]:
ytest

array(['0', '1', '0', ..., '0', '1', '1'], dtype=object)

In [46]:
model.score(x_test,ytest)

0.9904013961605584

# prediction

In [48]:
emails = ['hey i am lokking for machine learning tutorial in begali language','hey you win an iphone x giveaway for free please do the survey']

In [49]:
cv_emails = cv.transform(emails)

In [50]:
model.predict(cv_emails)

array(['0', '1'], dtype='<U92')

# performance matrix


In [54]:
pred = model.predict(x_test)

In [55]:
pred

array(['0', '1', '0', ..., '0', '1', '1'], dtype='<U92')

# accuracy

In [57]:
from sklearn.metrics import accuracy_score

In [58]:
accuracy_score(ytest,pred)

0.9904013961605584

# confusion matrix

In [59]:
from sklearn.metrics import confusion_matrix

In [60]:
confusion_matrix(ytest,pred)

array([[  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  1,   1, 836,   4],
       [  0,   0,   5, 299]])

# report

In [62]:
from sklearn.metrics import classification_report

In [67]:
print(classification_report(ytest,pred))

                                                                                              precision    recall  f1-score   support

 its termination would not  have such a phenomenal impact on the power situation .  however        0.00      0.00      0.00         0
                                                                           mr suresh prabhu        0.00      0.00      0.00         0
                                                                                           0       0.99      0.99      0.99       842
                                                                                           1       0.99      0.98      0.99       304

                                                                                    accuracy                           0.99      1146
                                                                                   macro avg       0.50      0.49      0.49      1146
                                                            